services:
  - type: web
    name: ai-dev-toolkit
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/ai-dev-toolkit-1.0.0.jar
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
    healthCheckPath: /actuator/health

