server:
  port: 8080

spring:
  application:
    name: ai-dev-toolkit

ai:
  openai:
    api-key: ${OPENAI_API_KEY:your-api-key-here}
    api-url: https://api.openai.com/v1/chat/completions
    model: gpt-3.5-turbo
    max-tokens: 2000
    temperature: 0.3

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.steedware.toolkit: INFO
    org.springframework.web: DEBUG
