server:
  port: ${PORT:8080}
  compression:
    enabled: true
  http2:
    enabled: true

spring:
  application:
    name: ai-dev-toolkit
  jpa:
    show-sql: false
  output:
    ansi:
      enabled: never

ai:
  openai:
    api-key: ${OPENAI_API_KEY}
    api-url: https://api.openai.com/v1/chat/completions
    model: gpt-3.5-turbo
    max-tokens: 2000
    temperature: 0.3

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    com.steedware.toolkit: INFO
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
